// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4vdrbsycKEVQq8eeHcLAyzlTGS_SsXs',
    appId: '1:905297662812:web:539f5dd0080434f75c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    authDomain: 'health-assistant-a4ab2.firebaseapp.com',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    measurementId: 'G-8RXFHRRX3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSM_vBspKrcFFgq5kuQTenZtAQlA7Or4',
    appId: '1:905297662812:android:ef593e4fc3a409fb5c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqFjFHXucjOG7WhITRLFohZiyqeEdPGM',
    appId: '1:905297662812:ios:faa1ab2e7a5912dc5c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    iosClientId: '905297662812-k3sj74l9ekp5nlcgn79hmg964job735u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqFjFHXucjOG7WhITRLFohZiyqeEdPGM',
    appId: '1:905297662812:ios:faa1ab2e7a5912dc5c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    iosClientId: '905297662812-k3sj74l9ekp5nlcgn79hmg964job735u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-4vdrbsycKEVQq8eeHcLAyzlTGS_SsXs',
    appId: '1:905297662812:web:4a6da30bb709ebac5c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    authDomain: 'health-assistant-a4ab2.firebaseapp.com',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    measurementId: 'G-DQ2X1RQ8DS',
  );

}