// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4vdrbsycKEVQq8eeHcLAyzlTGS_SsXs',
    appId: '1:905297662812:web:c8bab3046172c6d85c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    authDomain: 'health-assistant-a4ab2.firebaseapp.com',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    measurementId: 'G-370K6ZR9WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSM_vBspKrcFFgq5kuQTenZtAQlA7Or4',
    appId: '1:905297662812:android:22d2fed412855bc05c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqFjFHXucjOG7WhITRLFohZiyqeEdPGM',
    appId: '1:905297662812:ios:e0f340cdd4312cdd5c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    androidClientId: '905297662812-6dkih4h36mg2mqrnruj8mdjpgu73g1va.apps.googleusercontent.com',
    iosClientId: '905297662812-k3sj74l9ekp5nlcgn79hmg964job735u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqFjFHXucjOG7WhITRLFohZiyqeEdPGM',
    appId: '1:905297662812:ios:e0f340cdd4312cdd5c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    androidClientId: '905297662812-6dkih4h36mg2mqrnruj8mdjpgu73g1va.apps.googleusercontent.com',
    iosClientId: '905297662812-k3sj74l9ekp5nlcgn79hmg964job735u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-4vdrbsycKEVQq8eeHcLAyzlTGS_SsXs',
    appId: '1:905297662812:web:773056735390e5405c6799',
    messagingSenderId: '905297662812',
    projectId: 'health-assistant-a4ab2',
    authDomain: 'health-assistant-a4ab2.firebaseapp.com',
    storageBucket: 'health-assistant-a4ab2.firebasestorage.app',
    measurementId: 'G-B1NS2JBN0J',
  );

}